version: '3.1'

services:
  demyst:
    container_name: demyst-web
    build: ./Demyst/docker
    restart: always
    ports:
      - 3000:3000
      - 3006:3006
    volumes:
      - ./Demyst:/var/www/html
    tty: true 
    depends_on:
      - db

  others:
    container_name: demyst-others
    build: ./ThirdPartSystems/docker
    restart: always
    environment:
      PORT: 4000
    ports:
      - 4000:4000
    volumes:
      - ./ThirdPartSystems/services:/var/www/html
    tty: true 
   
  db:  
    container_name: demyst-db
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
